network_ui/nw_handicaps/models.py
from network_ui import db


class NetworkHandicap(db.Model):
    __tablename__ = "networkhandicaps"

    id = db.Column(db.Integer, primary_key=True)

    cidr_not = db.Column(db.Text)  # Eg: 192.168.1.1/23

    handicap_name = db.Column(db.Text, unique=True)  # Eg: good network

    bandwidth_restriction_upload = db.Column(db.Float)
    bandwidth_restriction_download = db.Column(db.Float)

    dns_latency = db.Column(db.Float)
    general_latency = db.Column(db.Float)
    packet_loss = db.Column(db.Float)

    # this is to hold the total number of pcs configured for a template
    # ? Question: is this a better way or joining 2 tables and counting is better?
    no_of_pcs = db.Column(db.Integer, default=0)

    # https://docs.sqlalchemy.org/en/14/orm/cascades.html
    # cascade will auto delete the child when the parent is deleted
    ip_address_id = db.relationship(
        "IPAddress",
        backref="networkhandicaps",
        cascade="all, delete-orphan",
        lazy="dynamic",
    )

    def __init__(
        self,
        handicap_name,
        bandwidth_restriction_upload,
        bandwidth_restriction_download,
        dns_latency,
        general_latency,
        packet_loss,
        cidr_not,
    ):
        self.handicap_name = handicap_name
        self.bandwidth_restriction_upload = bandwidth_restriction_upload
        self.bandwidth_restriction_download = bandwidth_restriction_download
        self.dns_latency = dns_latency
        self.general_latency = general_latency
        self.packet_loss = packet_loss
        self.cidr_not = cidr_not

network_ui/nw_handicaps/forms.py
from flask_wtf import FlaskForm
from wtforms import IntegerField, StringField, SubmitField, FloatField
from wtforms.validators import InputRequired, Optional


class AddForm(FlaskForm):
    nw_handicap_name = StringField(
        "Name of handicap template:", validators=[InputRequired()]
    )
    bandwidth_restriction_upload = FloatField(
        "Enter Bandwidth restriction - max upload:", validators=[Optional()]
    )
    bandwidth_restriction_download = FloatField(
        "Enter Bandwidth restriction - max download:", validators=[Optional()]
    )
    dns_latency = FloatField("DNS Latency (In seconds):", validators=[Optional()])
    general_latency = FloatField(
        "General Latency (In seconds):", validators=[Optional()]
    )

    packet_loss = FloatField("Packet Loss %:", validators=[InputRequired()])

    cidr_not_ip = StringField("Enter the IP address: ", validators=[Optional()])
    cidr_suffix = StringField("Enter the suffix: ", validators=[Optional()])

    submit = SubmitField("Add handicap template")

network_ui/nw_handicaps/views.py
from network_ui import db
from network_ui.nw_handicaps.forms import AddForm
from network_ui.nw_handicaps.models import NetworkHandicap
from flask import Blueprint, render_template, url_for, redirect, flash, request
from markupsafe import Markup
from network_ui.helpers.helpers_common import validate_ip_address

nw_handicap_blueprint = Blueprint(
    "nw_handi", __name__, template_folder="templates/nw_handicaps/"
)


@nw_handicap_blueprint.route("/add", methods=["GET", "POST"])
def add():
    form = AddForm()

    if form.validate_on_submit():
        handicap_name = form.nw_handicap_name.data
        bandwidth_restriction_upload = form.bandwidth_restriction_upload.data
        bandwidth_restriction_download = form.bandwidth_restriction_download.data

        dns_latency = form.dns_latency.data
        general_latency = form.general_latency.data

        packet_loss = form.packet_loss.data

        cidr_notation = None

        if form.cidr_not_ip.data and form.cidr_suffix.data:
            if validate_ip_address(form.cidr_not_ip.data):
                cidr_notation = f"{form.cidr_not_ip.data}/{form.cidr_suffix.data}"
                print(cidr_notation)
            else:
                cidr_notation = None
                flash(
                    Markup(
                        f"the ip address you entered is wrong > '<b>{form.cidr_not_ip.data}</b>'"
                    ),
                    "danger",
                )

                return redirect(url_for("nw_handi.add"))

        elif form.cidr_not_ip.data and not form.cidr_suffix.data:

            flash(
                Markup(f"Add the suffix {form.cidr_not_ip.data} / <b>----</b>"),
                "warning",
            )

            return redirect(url_for("nw_handi.add"))

        # check the Handicap name is already existing on DB
        if NetworkHandicap.query.filter_by(handicap_name=handicap_name).first() != None:
            flash(
                Markup(f"This handicap name <b>{handicap_name}</b> is already in use"),
                "danger",
            )
            return redirect(url_for("nw_handi.add"))

        new_nw_handicap = NetworkHandicap(
            handicap_name,
            bandwidth_restriction_upload,
            bandwidth_restriction_download,
            dns_latency,
            general_latency,
            packet_loss,
            cidr_notation,
        )

        db.session.add(new_nw_handicap)
        db.session.commit()

        return redirect(url_for("index"))
    if request.method == "POST":
        flash(
            "Enter value for at least one parameter to save the handicap template",
            "danger",
        )
    return render_template("add_nw_handicap.html", form=form)


@nw_handicap_blueprint.route("/list", methods=["GET", "POST"])
def list():
    nw_handicaps = NetworkHandicap.query.all()

    return render_template("list_all_handicaps.html", nw_handicaps=nw_handicaps)


@nw_handicap_blueprint.route("/delete/<int:id>", methods=["GET", "POST"])
def delete(id):
    ip_address = NetworkHandicap.query.get(id)
    if ip_address:
        db.session.delete(ip_address)
        db.session.commit()

        # TODO: Add a script call to remove this IP address from the restriction
        # TODO: along with the template deletion, delete all the IP address configured with the template
    return redirect(url_for("nw_handi.list"))


@nw_handicap_blueprint.route("/update/<int:id>", methods=["GET", "POST"])
def update(id):
    form = AddForm()

    handicap_to_update = NetworkHandicap.query.get_or_404(id)

    if form.validate_on_submit():

        updated_handicap_name = form.nw_handicap_name.data

        # check the Handicap name is already existing on DB
        if (
            NetworkHandicap.query.filter_by(handicap_name=updated_handicap_name).first()
            != None
            and handicap_to_update.handicap_name != updated_handicap_name
        ):
            flash(
                Markup(
                    f"This handicap name <b>{form.nw_handicap_name.data}</b> is already in use"
                ),
                "danger",
            )
            return redirect(url_for("nw_handi.list"))

        handicap_to_update.handicap_name = form.nw_handicap_name.data
        handicap_to_update.bandwidth_restriction_upload = (
            form.bandwidth_restriction_upload.data
        )
        handicap_to_update.bandwidth_restriction_download = (
            form.bandwidth_restriction_download.data
        )

        handicap_to_update.dns_latency = form.dns_latency.data
        handicap_to_update.general_latency = form.general_latency.data

        handicap_to_update.packet_loss = form.packet_loss.data

        cidr_notation = None

        if form.cidr_not_ip.data and form.cidr_suffix.data:
            if validate_ip_address(form.cidr_not_ip.data):
                cidr_notation = f"{form.cidr_not_ip.data}/{form.cidr_suffix.data}"
                print(cidr_notation)
            else:
                cidr_notation = None
                flash(
                    Markup(
                        f"the ip address you entered is wrong > '<b>{form.cidr_not_ip.data}</b>'"
                    ),
                    "danger",
                )

                return redirect(url_for("nw_handi.update", id=id))

        elif form.cidr_not_ip.data and not form.cidr_suffix.data:

            flash(
                Markup(f"Add the suffix {form.cidr_not_ip.data} / <b>----</b>"),
                "warning",
            )

            return redirect(url_for("nw_handi.update", id=id))

        handicap_to_update.cidr_not = cidr_notation

        db.session.commit()
        flash(
            Markup(f"<b>{handicap_to_update.handicap_name}</b> updated successfully"),
            "success",
        )
        return redirect(url_for("nw_handi.list"))
    return render_template(
        "update_nw_handicap.html", form=form, handicap_to_update=handicap_to_update
    )

network_ui/nw_handicaps/templates/nw_handicaps/add_nw_handicap.html
{% extends "base.html" %}

{% block content %}

<div class="col">
    <h2>Add a network handicap template</h2>
    <form method="POST" novalidate class="needs-validation">
        {{form.hidden_tag()}}

        {{form.nw_handicap_name.label(class="form-label")}}<br>
        <div class="input-group has-validation">
            {{form.nw_handicap_name(class="form-control", required="required", placeholder="Good Network")}}
            <div class="valid-feedback">Looks good!</div>
            <div class="invalid-feedback">Please enter a name for the network handicap.</div>
        </div><br>

        {{form.bandwidth_restriction_upload.label(class="form-label")}}<br>
        <div class="input-group has-validation">
            {{form.bandwidth_restriction_upload(class="form-control", type="number", min=0, placeholder="optional")}}
            <div class="valid-feedback">Looks good!</div>
            <div class="invalid-feedback">Stop QA'ing and enter a NUMBER</div>
        </div><br>

        {{form.bandwidth_restriction_download.label(class="form-label")}}<br>
        <div class="input-group has-validation">
            {{form.bandwidth_restriction_download(class="form-control", type="number", min=0, placeholder="optional")}}
            <div class="valid-feedback">Looks good!</div>
            <div class="invalid-feedback">Stop QA'ing and enter a NUMBER</div>
        </div><br>

        {{form.dns_latency.label(class="form-label")}}<br>
        <div class="input-group has-validation">
            {{form.dns_latency(class="form-control", type="number", min=0, placeholder="optional")}}
            <div class="valid-feedback">Looks good!</div>
            <div class="invalid-feedback">Stop QA'ing and enter a NUMBER</div>
        </div><br>

        {{form.general_latency.label(class="form-label")}}<br>
        <div class="input-group has-validation">
            {{form.general_latency(class="form-control", type="number", min=0, placeholder="optional")}}
            <div class="valid-feedback">Looks good!</div>
            <div class="invalid-feedback">Stop QA'ing and enter a NUMBER</div>
        </div><br>

        {{form.packet_loss.label(class="form-label")}}<br>
        <div class="input-group has-validation">
            {{form.packet_loss(class="form-control", type="number", min=0, max=100, value=0, placeholder="default value 0")}}
            <div class="valid-feedback">Looks good!</div>
            <div class="invalid-feedback">Stop QA'ing and enter a NUMBER</div>
        </div><br>

        <div class="form-label">Enter the subnet in CIDR notation eg: 192.168.1.1 <b>/</b> 24</div>
        <div class="row row-cols-auto">
            <div class="col">
                <div class="input-group has-validation">
                    {{form.cidr_not_ip(class="form-control", placeholder="192.168.1.1 (optional)")}}
                    <div class="valid-feedback">Looks good!</div>
                    <div class="invalid-feedback">Stop QA'ing and enter a NUMBER</div>
                </div>
            </div>
            <div class="col">
                <b>/</b>
            </div>
            <div class="col">
                <div class="input-group has-validation">
                    {{form.cidr_suffix(class="form-control", type="number", min=0, max=32, placeholder="30 (optional)")}}
                    <div class="valid-feedback">Looks good!</div>
                    <div class="invalid-feedback">Enter a valid number between 0 - 32</div>
                </div>
            </div>
        </div><br>


        {{form.submit(class="btn btn-outline-primary")}}
    </form>
</div>

<script>

    // JavaScript for disabling form submissions if there are invalid fields
    (() => {
        'use strict'

        // Fetch all the forms we want to apply custom Bootstrap validation styles to
        const forms = document.querySelectorAll('.needs-validation')

        // Loop over them and prevent submission
        Array.from(forms).forEach(form => {
            form.addEventListener('submit', event => {
                if (!form.checkValidity()) {
                    event.preventDefault()
                    event.stopPropagation()
                }

                form.classList.add('was-validated')
            }, false)
        })
    })()
</script>

{% endblock content %}

network_ui/nw_handicaps/templates/nw_handicaps/list_all_handicaps.html
{% extends "base.html" %}

{% block content %}


<div class="card">
    <div class="card-body">
        {% if nw_handicaps %}

        <table class="table table-bordered">
            <thead>
                <tr>
                    <th scope="col">#</th>
                    <th scope="col">Handicap Name <div style="font-weight: normal; font-size: small;">SubNet mask</div>
                    </th>
                    <th scope="col">Bandwidth restriction (max upload, max download)</th>
                    <th scope="col">DNS Latency</th>
                    <th scope="col">General Latency</th>
                    <th scope="col">Packet Loss %</th>
                    <th scope="col">Number of PCs</th>
                    <th scope="col"></th>
                </tr>
            </thead>
            <tbody>
                {% for nw_handicap in nw_handicaps %}
                <tr>
                    <th scope="row">{{loop.index}}</th>
                    <td><b>{{nw_handicap.handicap_name}}</b><br>
                        {% if nw_handicap.cidr_not %}
                        <div style="font-size: small;">{{nw_handicap.cidr_not}}</div>
                        {% endif %}
                    </td>
                    <td>{{nw_handicap.bandwidth_restriction_upload ~ ' MB, ' if nw_handicap.bandwidth_restriction_upload
                        is not none else '--,'}} {{nw_handicap.bandwidth_restriction_download ~ ' MB, ' if
                        nw_handicap.bandwidth_restriction_download is not none else '--'}}
                    </td>
                    <td>{{nw_handicap.dns_latency if nw_handicap.dns_latency is not none else '--'}}</td>
                    <td>{{nw_handicap.general_latency if nw_handicap.general_latency is not none else '--'}}</td>
                    <td>{{nw_handicap.packet_loss if nw_handicap.packet_loss is not none else '--'}}</td>
                    <td>{{nw_handicap.no_of_pcs}}</td>
                    <td>
                        <div style="width: max-content;">
                            <button type="button" class="btn btn-outline-danger" data-bs-toggle="modal" data-bs-target="#deleteTemplateConfirm{{nw_handicap.id}}">
                                Delete
                            </button>
                            <!-- Modal -->
                            <div class="modal fade" id="deleteTemplateConfirm{{nw_handicap.id}}" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
                                <div class="modal-dialog modal-dialog-centered">
                                    <div class="modal-content">
                                        <div class="modal-header">
                                            <h1 class="modal-title fs-5" id="exampleModalLabel">Delete
                                                <b>{{nw_handicap.handicap_name}}?</b>
                                            </h1>
                                            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                                        </div>
                                        <div class="modal-body">
                                            Are you sure you wanted to delete "{{nw_handicap.handicap_name}}?"
                                            {% if nw_handicap.no_of_pcs | int > 1 %} <u>This is going to affect
                                                {{nw_handicap.no_of_pcs}} devices</u>
                                            {% elif nw_handicap.no_of_pcs | int == 1 %}
                                            <u>This is going to affect {{nw_handicap.no_of_pcs}} device</u>
                                            {% else %}
                                            {% endif %}
                                        </div>
                                        <div class="modal-footer">
                                            <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                                            <a href="{{ url_for('nw_handi.delete', id=nw_handicap.id) }}" type="button" class="btn btn-danger">Delete, I fear no
                                                man</a>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <a class="btn btn-outline-warning" href="{{ url_for('nw_handi.update', id=nw_handicap.id) }}">Edit</a>
                        </div>
                    </td>
                    {# old button without confirmation #}
                    {# <td><a href="{{ url_for('nw_handi.delete', id=nw_handicap.id) }}" type="button" class="btn btn-outline-danger">delete</a><br></td> #}
                </tr>

                {% endfor%}

            </tbody>
        </table>
        {% else %}
        <h2>No Network Handicaps added yet</h2>
        {% endif %}
    </div>
</div>

{% endblock content %}

network_ui/nw_handicaps/templates/nw_handicaps/update_nw_handicap.html
{% extends "base.html" %}

{% block content %}

<div class="col">
    <h2>Update "<b>{{handicap_to_update.handicap_name}}</b>"</h2><br>
    <form method="POST" novalidate class="needs-validation">
        {{form.hidden_tag()}}

        {{form.nw_handicap_name.label(class="form-label")}}<br>
        <div class="input-group has-validation">
            {{form.nw_handicap_name(class="form-control", required="required", value = handicap_to_update.handicap_name
            )}}<br>
            <div class="valid-feedback">Looks good!</div>
            <div class="invalid-feedback">Please enter a name for the network handicap.</div>
        </div>

        {{form.bandwidth_restriction_upload.label(class="form-label")}}<br>
        <div class="input-group has-validation">
            {{form.bandwidth_restriction_upload(class="form-control", type="number", min=0,
            value=handicap_to_update.bandwidth_restriction_upload)}}
            <div class="valid-feedback">Looks good!</div>
            <div class="invalid-feedback">Stop QA'ing and enter a NUMBER</div>
        </div><br>

        {{form.bandwidth_restriction_download.label(class="form-label")}}<br>
        <div class="input-group has-validation">
            {{form.bandwidth_restriction_download(class="form-control", type="number", min=0,
            value=handicap_to_update.bandwidth_restriction_download)}}
            <div class="valid-feedback">Looks good!</div>
            <div class="invalid-feedback">Stop QA'ing and enter a NUMBER</div>
        </div><br>

        {{form.dns_latency.label(class="form-label")}}<br>
        <div class="input-group has-validation">
            {{form.dns_latency(class="form-control", type="number", min=0, value=handicap_to_update.dns_latency)}}
            <div class="valid-feedback">Looks good!</div>
            <div class="invalid-feedback">Stop QA'ing and enter a NUMBER</div>
        </div><br>

        {{form.general_latency.label(class="form-label")}}<br>
        <div class="input-group has-validation">
            {{form.general_latency(class="form-control", type="number", min=0,
            value=handicap_to_update.general_latency)}}
            <div class="valid-feedback">Looks good!</div>
            <div class="invalid-feedback">Stop QA'ing and enter a NUMBER</div>
        </div><br>

        {{form.packet_loss.label(class="form-label")}}<br>
        <div class="input-group has-validation">
            {{form.packet_loss(class="form-control", type="number", min=0, max=100,
            value=handicap_to_update.packet_loss)}}
            <div class="valid-feedback">Looks good!</div>
            <div class="invalid-feedback">Stop QA'ing and enter a NUMBER</div>
        </div><br>

        <div class="form-label">Enter the subnet in CIDR notation eg: 192.168.1.1 <b>/</b> 24</div>
        <div class="row row-cols-auto">
            <div class="col">
                <div class="input-group has-validation">
                    {{form.cidr_not_ip(class="form-control", placeholder="192.168.1.1 (optional)", value=handicap_to_update.cidr_not.split('/')[0] if handicap_to_update.cidr_not)}}
                    <div class="valid-feedback">Looks good!</div>
                    <div class="invalid-feedback">Stop QA'ing and enter a NUMBER</div>
                </div>
            </div>
            <div class="col">
                <b>/</b>
            </div>
            <div class="col">
                <div class="input-group has-validation">
                    {{form.cidr_suffix(class="form-control", type="number", min=0, max=32, placeholder="30 (optional)", value=handicap_to_update.cidr_not.split('/')[1] if handicap_to_update.cidr_not)}}
                    <div class="valid-feedback">Looks good!</div>
                    <div class="invalid-feedback">Enter a valid number between 0 - 32</div>
                </div>
            </div>
        </div><br>

        {{form.submit(class="btn btn-outline-primary", value="Update" )}}

        <a class="btn btn-outline-secondary" href="{{ url_for('nw_handi.list')}}">Cancel</a>

    </form>
</div>

<script>

    // JavaScript for disabling form submissions if there are invalid fields
    (() => {
        'use strict'

        // Fetch all the forms we want to apply custom Bootstrap validation styles to
        const forms = document.querySelectorAll('.needs-validation')

        // Loop over them and prevent submission
        Array.from(forms).forEach(form => {
            form.addEventListener('submit', event => {
                if (!form.checkValidity()) {
                    event.preventDefault()
                    event.stopPropagation()
                }

                form.classList.add('was-validated')
            }, false)
        })
    })()
</script>

{% endblock content %}