network_ui/ip_addresses/views.py
import subprocess
from network_ui import db
from markupsafe import Markup
from network_ui.ip_addresses.forms import AddForm
from network_ui.ip_addresses.models import IPAddress
from network_ui.nw_handicaps.models import NetworkHandicap
from flask import Blueprint, render_template, url_for, redirect, flash
from network_ui.helpers.helpers_common import (
    validate_ip_address,
    ip_mask_calculations,
    check_ip_belongs_subnet,
)

ip_address_blueprint = Blueprint(
    "ipaddresses", __name__, template_folder="templates/ip_addresses/"
)


# this flag is to prevent multiple users from running script simultaniously
# Ask help for a better implementaion of this.
is_a_scrip_running = False


@ip_address_blueprint.route("/add", methods=["GET", "POST"])
def add():
    global is_a_scrip_running

    form = AddForm()

    handicaps_and_subnets = NetworkHandicap.query.with_entities(
        NetworkHandicap.handicap_name, NetworkHandicap.cidr_not
    )
    subnets = {
        handicap_name: ip_mask_calculations(cidr_not)["limit"]
        for handicap_name, cidr_not in handicaps_and_subnets
        if cidr_not
    }

    form.network_handicap.choices = [
        (g.id, g.handicap_name) for g in NetworkHandicap.query.all()
    ]

    # if a script is running already take the user to the homescreen and show a flash
    if is_a_scrip_running:
        flash("a script is running please wait before adding a new one", "danger")
        return redirect(url_for("index"))

    if form.validate_on_submit():

        pc_name = form.pc_name.data
        ip_address = form.ip_address.data
        network_handicap = form.network_handicap.data

        # check the PC name is already existing on DB
        if IPAddress.query.filter_by(pc_name=pc_name).first() != None:
            flash(
                Markup(f"This PC name <b>{pc_name}</b> is already in use"),
                "danger",
            )
            return redirect(url_for("ipaddresses.add"))
        # check the IP Address is already existing on DB
        if IPAddress.query.filter_by(ip_address=ip_address).first() != None:
            flash(
                Markup(f"This IP address <b>{ip_address}</b> is already in use"),
                "danger",
            )
            return redirect(url_for("ipaddresses.add"))

        selected_nw_handicap = NetworkHandicap.query.get(network_handicap)

        # Check the IP addr is a valid one or not
        # if valid continue saving it
        if validate_ip_address(ip_address):
            if selected_nw_handicap.cidr_not is not None:
                if not check_ip_belongs_subnet(
                    ip_address, selected_nw_handicap.cidr_not
                ):
                    flash(
                        Markup(
                            f"'{ip_address}' is not belong to the proper Sub Net of '{selected_nw_handicap.handicap_name}'"
                        ),
                        "danger",
                    )
                    return redirect(url_for("ipaddresses.add"))
            # run the script with subprocess and if it is succesful, add the details to DB
            is_a_scrip_running = True

            # commenting to test this on windows
            # script_call = subprocess.call(
            #     [
            #         "bash",
            #         "network_ui/shell_scripts/temp.sh",
            #         str(ip_address),
            #         str(network_handicap),
            #     ]
            # )

            script_call = 0

            if str(script_call) == "0":
                is_a_scrip_running = False

            # Increment the total number PCs configured in this template by 1
            # Please see the question on nw_handicaps > models.py
            NetworkHandicap.query.get(int(network_handicap)).no_of_pcs = (
                NetworkHandicap.query.get(int(network_handicap)).no_of_pcs + 1
            )

            new_ip_address = IPAddress(pc_name, ip_address, network_handicap)
            db.session.add(new_ip_address)
            db.session.commit()

            flash(Markup(f"IP address added successfully"), "success")
            return redirect(url_for("index"))

        else:
            flash(Markup(f"{ip_address} is not a valid IP address"), "danger")

    # if the network handicap is empty, ask the user to add one first before adding an ip
    if NetworkHandicap.query.all() == []:
        flash("Add a Network Profile first to add an ip address", "warning")
        return redirect(url_for("nw_handi.add"))

    return render_template("add_ip_address.html", form=form, subnets=subnets)


@ip_address_blueprint.route("/delete/<int:id>", methods=["GET", "POST"])
def delete(id):
    ip_address = IPAddress.query.get(id)
    if ip_address:

        # Decrement the total number PCs configured in this template by 1
        # Please see the question on nw_handicaps > models.py
        NetworkHandicap.query.get(int(ip_address.network_handicap)).no_of_pcs = (
            NetworkHandicap.query.get(int(ip_address.network_handicap)).no_of_pcs - 1
        )

        db.session.delete(ip_address)
        db.session.commit()

        # TODO: Add a script call to remove this IP address from the restriction

    return redirect(url_for("index"))


@ip_address_blueprint.route("/update/<int:id>", methods=["GET", "POST"])
def update(id):
    global is_a_scrip_running

    form = AddForm()

    handicaps_and_subnets = NetworkHandicap.query.with_entities(
        NetworkHandicap.handicap_name, NetworkHandicap.cidr_not
    )

    subnets = {
        handicap_name: ip_mask_calculations(cidr_not)["limit"]
        for handicap_name, cidr_not in handicaps_and_subnets
        if cidr_not
    }

    form.network_handicap.choices = [
        (g.id, g.handicap_name) for g in NetworkHandicap.query.all()
    ]

    # form.network_handicap.choices.pop(form.network_handicap.data)

    ip_addr_to_update = IPAddress.query.get_or_404(id)
    current_nw_profile = ip_addr_to_update.network_handicap

    # if a script is running already take the user to the homescreen and show a flash
    if is_a_scrip_running:
        flash("a script is running please wait before adding a new one", "danger")
        return redirect(url_for("index"))

    if form.validate_on_submit():
        updated_pc_name = form.pc_name.data
        updated_ip_address = form.ip_address.data
        updated_network_handicap = form.network_handicap.data

        # check the updated PC name is already existing on DB
        if (
            IPAddress.query.filter_by(pc_name=updated_pc_name).first() != None
            and ip_addr_to_update.pc_name != updated_pc_name
        ):
            flash(
                Markup(f"This PC name <b>{updated_pc_name}</b> is already in use"),
                "danger",
            )
            return redirect(url_for("ipaddresses.update", id=id))
        # check the updated IP Address is already existing on DB
        if (
            IPAddress.query.filter_by(ip_address=updated_ip_address).first() != None
            and ip_addr_to_update.ip_address != updated_ip_address
        ):
            flash(
                Markup(
                    f"This IP address <b>{updated_ip_address}</b> is already in use"
                ),
                "danger",
            )
            return redirect(url_for("ipaddresses.update", id=id))

        selected_nw_handicap = NetworkHandicap.query.get(updated_network_handicap)

        # Check the IP addr is a valid one or not
        # if valid continue saving it
        if validate_ip_address(updated_ip_address):
            if selected_nw_handicap.cidr_not is not None:
                if not check_ip_belongs_subnet(
                    updated_ip_address, selected_nw_handicap.cidr_not
                ):
                    flash(
                        Markup(
                            f"'{updated_ip_address}' is not belong to the proper Sub Net of '{selected_nw_handicap.handicap_name}'"
                        ),
                        "danger",
                    )
                    return redirect(url_for("ipaddresses.update", id=id))
            # run the script with subprocess and if it is succesful, add the details to DB
            is_a_scrip_running = True

            # commenting to test this on windows
            # script_call = subprocess.call(
            #     [
            #         "bash",
            #         "network_ui/shell_scripts/temp.sh",
            #         str(ip_address),
            #         str(network_handicap),
            #     ]
            # )

            script_call = 0

            if str(script_call) == "0":
                is_a_scrip_running = False

            ip_addr_to_update.pc_name = updated_pc_name
            ip_addr_to_update.ip_address = updated_ip_address
            ip_addr_to_update.network_handicap = updated_network_handicap

            # Increment the total number PCs configured in this template by 1
            # Please see the question on nw_handicaps > models.py
            NetworkHandicap.query.get(int(updated_network_handicap)).no_of_pcs = (
                NetworkHandicap.query.get(int(updated_network_handicap)).no_of_pcs + 1
            )

            db.session.commit()

            flash(Markup(f"IP address added successfully"), "success")
            return redirect(url_for("index"))

        else:
            flash(Markup(f"{updated_ip_address} is not a valid IP address"), "danger")

    # if the network handicap is empty, ask the user to add one first before adding an ip
    if NetworkHandicap.query.all() == []:
        flash("Add a Network Profile first to add an ip address", "warning")
        return redirect(url_for("nw_handi.update", id=id))

    return render_template(
        "update_ip_address.html",
        form=form,
        subnets=subnets,
        ip_addr_to_update=ip_addr_to_update,
    )

network_ui/templates/base.html
<!DOCTYPE html>
<html>
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" />
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.js"></script>

<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark sticky-top">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="{{url_for('index')}}">Home</a>
            </li>
            <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="{{url_for('ipaddresses.add')}}">Add IP Address</a>
            </li>
            <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="{{url_for('nw_handi.add')}}">Add network
                    template</a>
            </li>
            <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="{{url_for('nw_handi.list')}}">List all network
                    templates</a>
            </li>
        </ul>
    </nav>
    <div class="container py-4">
        <div class="p-5 mb-4 bg-light rounded-3">
            <div class="container-fluid"></div>

            {# flash messages #}
            {% for category, message in get_flashed_messages(with_categories=true)%}
            <div class="alert alert-{{category}} alert-dismissible fade show" role="alert">
                {{message}}
                <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
            </div>
            {% endfor %}

            {% block content %}

            {% endblock content %}

        </div>
    </div>
    </div>


    <!--- https://getbootstrap.com/docs/5.0/components/popovers/#example-enable-popovers-everywhere -->
    <script>
        var popoverTriggerList = [].slice.call(document.querySelectorAll('[data-bs-toggle="popover"]'))
        var popoverList = popoverTriggerList.map(function (popoverTriggerEl) {
            return new bootstrap.Popover(popoverTriggerEl)
        })
    </script>

</body>

</html>

network_ui/templates/home.html
{% extends "base.html" %}


{% block content %}

<script>
    const getRandomEmoji = () => {
        const emojis = ['🐵', '🐒', '🦍', '🦧', '🐔', '🐓', '🐣', '🐤', '🐌', '🦋', '🐛', '🐜', '🐝', '🍇', '🍆', '🐞', '🦗', '🕷']
        return emojis[~~(Math.random() * emojis.length)]
    }
</script>

<div class="card">
    <div class="card-body">
        {% if templates[1] %}

        <form method="POST">

            <h2><em>List of configured PCs</em></h2><br>
            {% for _, template_items in templates.items() %}
            <div class="card-header">
                {# template name #}
                <h2 style="display: inline-block" data-bs-container="body" data-bs-trigger="hover" data-bs-toggle="popover" data-bs-placement="top" data-bs-html="true" data-bs-content="
                    <b>Bandwidth</b> Up: {{template_items['template'].bandwidth_restriction_upload}} / Down: {{template_items['template'].bandwidth_restriction_download}}<br>
                    <b>DNS Latency:</b> {{template_items['template'].dns_latency}}<br>
                    <b>General Latency: </b> {{template_items['template'].general_latency}}<br>
                    <b>Packet Loss: </b>{{template_items['template'].packet_loss}}%<br>
                    {% if template_items['template'].cidr_not %}<b>SubNet Mask: </b> {{template_items['template'].cidr_not }} {% endif %}
                    ">
                    {{template_items['template'].handicap_name}}<sup id="emoji-{{loop.index}}" style="vertical-align: super; font-size: small"></sup></h2>
                <script> document.getElementById("emoji-{{loop.index}}").innerHTML = getRandomEmoji()</script>
            </div>
            <table class="table table-bordered">
                <thead>
                    <tr>
                        <th scope="col">#</th>
                        <th scope="col">PC Name</th>
                        <th scope="col">IP Address</th>
                        <th scope="col"></th>
                    </tr>
                </thead>
                <tbody>
                    {% for template_item in template_items['pc'] %}
                    <tr>
                        {# {{loop.index}} is something like enumerate in python #}
                        <th scope="row">{{loop.index}}</th>
                        <td>{{template_item[0].pc_name}}</td>
                        <td>{{template_item[0].ip_address}}</td>
                        <td><button type="button" class="btn btn-outline-danger" data-bs-toggle="modal" data-bs-target="#deleteIPConfirm">Delete</button>
                            <!-- Modal -->
                            <div class="modal fade" id="deleteIPConfirm" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
                                <div class="modal-dialog modal-dialog-centered">
                                    <div class="modal-content">
                                        <div class="modal-header">
                                            <h1 class="modal-title fs-5" id="exampleModalLabel">Delete
                                                <b>{{template_item[0].pc_name}}?</b>
                                            </h1>
                                            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                                        </div>
                                        <div class="modal-body">
                                            These are the configured values:
                                            <p>
                                                <br>
                                                <b>Bandwidth</b> Up:
                                                {{template_items['template'].bandwidth_restriction_upload}} / Down:
                                                {{template_items['template'].bandwidth_restriction_download}}<br>
                                                <b>DNS Latency:</b> {{template_items['template'].dns_latency}}<br>
                                                <b>General Latency: </b>
                                                {{template_items['template'].general_latency}}<br>
                                                <b>Packet Loss: </b>{{template_items['template'].packet_loss}}%<br><br>
                                                <b>Ip Address:</b> {{template_item[0].ip_address}}
                                            </p>
                                        </div>
                                        <div class="modal-footer">
                                            <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                                            <a href="{{ url_for('ipaddresses.delete', id=template_item[0].id) }}" type="button" class="btn btn-danger">Delete, I fear no
                                                man</a>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <a class="btn btn-outline-warning" href="{{ url_for('ipaddresses.update', id=template_item[0].id) }}">Edit</a>
                        </td>

                        {# old button without delete confirmation #}
                        {# <td><a href="{{ url_for('ipaddresses.delete', id=template_item[0].id) }}" type="button" class="btn btn-outline-danger">delete</a><br></td> #}
                    </tr>
                    {% endfor %}
                </tbody>
            </table>

            <br><br>
            {% endfor %}
    </div>
    {% else %} <h2>No PCs configured yet</h2>

    {% endif %}
</div>
</form>

{% endblock content %}